# Generated by Django 5.1.4 on 2024-12-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_modificacao',
            new_name='data_atualizacao',
        ),
    ]
